### ISSUE TITLE
Integrate with existing ReactPHP Code

### ISSUE THREAD

**Issue by djsharman** [recoilphp/recoil#105]
Hi, 

I am looking at using recoilphp with some existing reactphp code that I have. The end point I want to get to is to yield for some DB queries, so that other users don't get held up by DB operations. 

Can you give me some pointers to get me going as I don't really see how to do this from the examples.

I had a quick scan through the code and information here on GitHub and I understood that you are using the reactPHP event loop. My initial attempt was to try to replace the existing reactphp event loop that I had with the recoilphp event loop. My code is a bit complex so I will use the ratchet sample code so show you roughly what I tried. 

Original code (from here: http://socketo.me/docs/push)

`<?php
    require dirname(__DIR__) . '/vendor/autoload.php';

    $loop   = React\EventLoop\Factory::create();
    $pusher = new MyApp\Pusher;

    // Listen for the web server to make a ZeroMQ push after an ajax request
    $context = new React\ZMQ\Context($loop);
    $pull = $context->getSocket(ZMQ::SOCKET_PULL);
    $pull->bind('tcp://127.0.0.1:5555'); // Binding to 127.0.0.1 means the only client that can connect is itself
    $pull->on('message', array($pusher, 'onBlogEntry'));

    // Set up our WebSocket server for clients wanting real-time updates
    $webSock = new React\Socket\Server($loop);
    $webSock->listen(8080, '0.0.0.0'); // Binding to 0.0.0.0 means remotes can connect
    $webServer = new Ratchet\Server\IoServer(
        new Ratchet\Http\HttpServer(
            new Ratchet\WebSocket\WsServer(
                new Ratchet\Wamp\WampServer(
                    $pusher
                )
            )
        ),
        $webSock
    );

    $loop->run();`

I modified this to something along the lines of:-

`<?php
    require dirname(__DIR__) . '/vendor/autoload.php';

        use Recoil\Recoil;
        use Recoil\React\ReactKernel;

	ReactKernel::start( function () {
	
		$loop = (yield \Recoil\Recoil::eventLoop());
		$pusher = new MyApp\Pusher;

		// Listen for the web server to make a ZeroMQ push after an ajax request
		$context = new React\ZMQ\Context($loop);
		$pull = $context->getSocket(ZMQ::SOCKET_PULL);
		$pull->bind('tcp://127.0.0.1:5555'); // Binding to 127.0.0.1 means the only client that can connect is itself
		$pull->on('message', array($pusher, 'onBlogEntry'));

		// Set up our WebSocket server for clients wanting real-time updates
		$webSock = new React\Socket\Server($loop);
		$webSock->listen(8080, '0.0.0.0'); // Binding to 0.0.0.0 means remotes can connect
		$webServer = new Ratchet\Server\IoServer(
			new Ratchet\Http\HttpServer(
				new Ratchet\WebSocket\WsServer(
					new Ratchet\Wamp\WampServer(
						$pusher
					)
				)
			),
			$webSock
		);
	
	});`

This ran but didn't seem to start the loop. So then I tried running the loop: 

`<?php
    require dirname(__DIR__) . '/vendor/autoload.php';

	ReactKernel::start( function () {
	
		$loop = (yield \Recoil\Recoil::eventLoop());
		$pusher = new MyApp\Pusher;

		// Listen for the web server to make a ZeroMQ push after an ajax request
		$context = new React\ZMQ\Context($loop);
		$pull = $context->getSocket(ZMQ::SOCKET_PULL);
		$pull->bind('tcp://127.0.0.1:5555'); // Binding to 127.0.0.1 means the only client that can connect is itself
		$pull->on('message', array($pusher, 'onBlogEntry'));

		// Set up our WebSocket server for clients wanting real-time updates
		$webSock = new React\Socket\Server($loop);
		$webSock->listen(8080, '0.0.0.0'); // Binding to 0.0.0.0 means remotes can connect
		$webServer = new Ratchet\Server\IoServer(
			new Ratchet\Http\HttpServer(
				new Ratchet\WebSocket\WsServer(
					new Ratchet\Wamp\WampServer(
						$pusher
					)
				)
			),
			$webSock
		);
		$loop->run(); // << NEW line added here
	});`

This worked as intended, but I have no idea if this how you expected things to be used. Is this the correct way of starting up your code?

Regards,

Darren

**Comment by jmalloc** [comment]
Hi Darren, thanks for your interest in Recoil :)

The issue is that `ReactKernel::start()` only blocks until the given coroutine (it's first parameter) completes. This is in contrast to previous versions of Recoil started via `Recoil::run()`. 

The intent here is that the application would have a main loop inside that "entry-point" coroutine, much like a conventional threaded application. That said, the behaviour you're after is still easily achievable, albeit not using the `::start()` method:

```php
$kernel = new RecoilKernel();
$kernel->execute(function () { /* ..... */ });
$kernel->wait();
```

Unlike `start()`, the `wait()` method wont terminate when that main coroutine returns.

I hope this helps, I realise now that the behaviour of `start()` is quite misleading. I apologise for not making this clear in the examples.
