### ISSUE TITLE
How to setup a HTTP server?

### ISSUE THREAD

**Issue by enumag** [recoilphp/recoil#164]
React PHP looks a bit useless because of all the `then` chains and callbacks so I'd like to use Recoil's Coroutines to make my code nicer.

However so far I'm unable to get even the basic example running on Recoil. What did I miss?

Here is an HTTP server hello world from react/http readme:

```php
$loop = React\EventLoop\Factory::create();

$server = new Server(function (ServerRequestInterface $request) {
    return new Response(
        200,
        array(
            'Content-Type' => 'text/plain'
        ),
        "Hello World!\n"
    );
});

$socket = new React\Socket\Server(8080, $loop);
$server->listen($socket);

$loop->run();
```

This works just fine, the script keeps running and responds to any HTTP request on the port 8080.

Now I tried to do the exact same thing with Recoil:

```php
ReactKernel::start(
    function () {
        $server = new Server(function (ServerRequestInterface $request) {
            return new Response(
                200,
                array(
                    'Content-Type' => 'text/plain'
                ),
                "Hello World!\n"
            );
        });

        $loop = yield Recoil::eventLoop();

        $socket = new \React\Socket\Server(8080, $loop);
        $server->listen($socket);
    }
);
```

But it doesn't work. The script finishes right away and does not keep running to listen for incoming connections like it should. What am I doing wrong?

**Comment by CharlotteDunois** [comment]
The problem in your script is that only the single coroutine is executed with [`ReactKernel::start()`](https://github.com/recoilphp/kernel/blob/53a469964b428224a8295ca44f4e330422319fdb/src/KernelTrait.php#L30) and as soon as it finishes the kernel will be stopped (there's nothing that keeps the coroutine running in your example).

You'd need to adjust your code to keep the coroutine running, potentially not using `ReactKernel::start` but instead creating a kernel and then running it normally with `ReactKernel->run()`, then you can just keep pushing coroutines onto the kernel.

Which means given a correct middleware callback for the Server will give you the power of `yield` within the Server callback. So potentially something like this:

```php
$loop = \React\EventLoop\Factory::create();
$kernel = ReactKernel::create($loop);

$handler = function (ServerRequestInterface $request): \Generator {
     // Do something like yielding
    // and processing the request
};

// We can return a promise and the server will wait for it to resolve
// See link below
$server = new Server(function (ServerRequestInterface $request) use ($kernel, $handler) {
    return $kernel->execute($handler($request))->promise();
});

$socket = new \React\Socket\Server(8080, $loop);
$server->listen($socket);

$kernel->run();
```
Link: <https://github.com/reactphp/http/blob/0eb598803db13f0994779fe450f33b95b3f04048/src/StreamingServer.php#L272>

**Comment by enumag** [comment]
I see. Looking into the code the difference is that this way the Kernel is created without a `MainStrandListener` which was what was stopping the loop in my example. Thanks.
