### ISSUE TITLE
Code is running too slow

### ISSUE THREAD

**Issue by Azhovan** [recoilphp/recoil#167]
Im not sure why the code is executing too much slow, I wrote this code to see how this library works in action 

```php 
use Recoil\React\ReactKernel;

function s1()
{
    for($j =10; $j<20; $j++) {
        echo "-- j:" .$j . "\n";
        yield $j;
    }
}
function s2()
{
    for($i =0; $i<10; $i++) {
        echo "++ j:" .$i . "\n";
        yield $i;
    }
}
// run it fron here 
ReactKernel::start(
    function (){
        yield  [ s2(), s1()];
        echo 'Done.' . PHP_EOL;
    }
);

```

what causes this issue?  Am I missing some thing?

**Comment by langabi** [comment]
`yield $j` where $j is an integer, is the Async equivalent of `sleep $j`, so this code will run for a long time, hundreds of seconds. If that’s not what you intended, then just remove the $j after the yield, ie just put` yield;`
